### PR TITLE
isDepositReadyForIngest, warning on nonfatal throwable ->

### PR DESCRIPTION
**Pull request by janvanmansum**
NO JIRA ISSUE.

### Description
If a non-fatal Throwable is encountered during the check, besides returning false, now also logging a warning

### How to test
You could create a non-readable deposit directory and start the dispatcher, which should subsequently get an exception when trying to check it, and log a warning.

### CODE REVIEW

**Comment by janvanmansum** [comment]
@DANS-KNAW/easy for review

**Comment by rvanheest** [comment]
Good addition, I think! However, what you're doing here is mix error handling and returning a default value. I think a better way of doing this is using the `doOnFailure` that is used in various other projects. As we do not have this one in the dans-scala-lib yet, would you mind annotating this `recover` with a TODO that refers to this comment and `doOnFailure`, such that we can find it back easily at a later time.

I'm currently thinking something along these lines:

```scala
Try {
    deposit.exists && deposit.isDirectory && depositStateIsSubmitted(deposit)
}.doOnFailure {
    case NonFatal(t) => log.warn(s"Could not determine if deposit is ready for ingest (assuming false): $deposit", t)
}.getOrElse(false)
```

I especially like the use of the `NonFatal` here. Maybe we should do that more often in our projects instead of `case e: Throwable` or `case e: Exception`!

**Comment by rvanheest** [comment]
Btw. now that we changed the dependencies on the other Scala projects back to `1.x-SNAPSHOT`, we get Travis errors again. @lindareijnhoudt and I were looking into this a bit yesterday and will be doing so in the next couples of weeks. We think we can configure Travis such that it deploys the snapshots on Artifactory as well... (inspiration: the `.travis.yml` file in [this repo](https://github.com/JakeWharton/RxRelay))

**Comment by janvanmansum** [comment]
@rvanheest : looks very promising. We should definitely have a look into that!

**Pull request merged**
